### ISSUE TITLE
Support Transactional Methods

### ISSUE THREAD

**Issue by chrisbarbour** [hexlabsio/dynamo-ts#18]

**Comment by ajotaos** [comment]
I was looking for this as well, great library and this is the feature I'm missing before using it. Or maybe is the documentation not available for these methods?

**Comment by chrisbarbour** [comment]
Part 1 of this is now complete, next step is to create a transactional getter

**Comment by chrisbarbour** [comment]
@ajotaos, this has now been added to the library, please See README for simple examples. The latest version has these changes: @hexlabs/dynamo-ts@6.0.173
