### ISSUE TITLE
Some Type are doesn't exported

### ISSUE THREAD

**Issue by chungtran-diqit** [hexlabsio/dynamo-ts#21]
For example `QueryKeys`, `QuerierInput`. I want to using it as directive for query param.

**Comment by chrisbarbour** [comment]
I have pushed a change to export all to the root so that you can import them with a simple import like this:
`import {QueryKeys} from '@hexlabs/dynamo-ts';`

You can make use of them today with the direct import like this:
`import { QueryKeys } from '@hexlabs/dynamo-ts/dist/dynamo-querier';`
