### ISSUE TITLE
Support All Attribute Types

### ISSUE THREAD

**Issue by ArcadeRenegade** [hexlabsio/dynamo-ts#22]
Thank you for this TS library.

I was trying to implement String Set as the type for one of my attributes but I noticed it is not in the `types.d.ts` file.

Could you support all the available attribute types as seen in the AWS documentation?

https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_AttributeValue.html

The ones I think are missing are:
- Binary (B)
- Binary Set (BS)
- Number Set (NS)
- String Set (SS)

**Comment by chrisbarbour** [comment]
Thanks for using the library, I have added support for sets and binary into the latest version.

**Comment by ArcadeRenegade** [comment]
@chrisbarbour just a heads up there seems to be a bug with optional sets where the value returned for the set attribute ends up being a `Partial<Set<T>>` in TypeScript. Which makes it difficult to utilize the `Set` features. Perhaps the value returned can be `Set<T> | undefined` instead?
