### ISSUE TITLE
scan/scanAll allow to use partitionKey and sortKey in filters

### ISSUE THREAD

**Issue by Dev-Rise** [hexlabsio/dynamo-ts#27]
Why `scan` and `scanAll` cannot use `filterPartsWithKey`? 
There are many cases for these methods that these filters should be available.
For example, I need to scan tables to find items that fulfill predicates for `someNormalKey` and `sortKey` (`partitionKey` is unknown). 
I tested the modified version which does not remove `partitionKey` and `sortKey` from filters, and it looks like everything works correctly. 

I can create PR with these changes, but I also want to know your opinion about that.

**Comment by chrisbarbour** [comment]
Thanks for this one! :)
