### ISSUE TITLE
Single Design Table question

### ISSUE THREAD

**Issue by obazoud** [hexlabsio/dynamo-ts#46]
Hello,

Thank for writing `dynamo-ts`.

A question about query in your [example](https://medium.com/hexlabs/typesafe-dynamodb-with-typescript-f0fe538186a7) with Repository and Workflow (Workflow with a join to Repository).

Let's say that we have these datas:

**Repository Table**
Partition                  |  Sort                  | ...
#ACCOUNT$acc1  |  #REPO$repo1 | ... other fields
#ACCOUNT$acc2 |  #REPO$repo2 | ... other fields

**Workflow Table**
Partition             |  Sort                                         | ...
#ACCOUNT$acc1  |  #WORKFLOW#REPO$repo1#WORKFLOW$wf1 | ... other fields
#ACCOUNT$acc1  |  #WORKFLOW#REPO$repo1#WORKFLOW$wf2 | ... other fields
#ACCOUNT$acc1  |  #WORKFLOW#REPO$repo1#WORKFLOW$wf3 | ... other fields
#ACCOUNT$acc2  |  #WORKFLOW#REPO$repo2#WORKFLOW$wf4| ... other fields
#ACCOUNT$acc2  |  #WORKFLOW#REPO$repo2#WORKFLOW$wf5 | ... other fields

In this modified example:
- the account _acc1_ owns a repository _repo1_ with 3 workflows _wf1_, _wf2_, _wf3_.
- the account _acc1_ owns a repository _repo2_ with 2 workflows _wf4_, _wf5_

With the API, we can get with all the repository with all the workflows as mentioned in the example.

For my use case, I would like also to get all the workflows for a given user and a given repo.

Does `dynamo-ts` be able to generate query like this ?
````
QueryInput: {
      "TableName": "singleTableDesignDefinition",
      "KeyConditionExpression": "#11 = :22  AND begins_with(#33, :44)",
      "ExpressionAttributeNames": {
        "#11": "partition",
        "#33": "sort"
      },
      "ExpressionAttributeValues": {
        ":22": "#ACCOUNT$acc1",
        ":44": "#WORKFLOW#REPO$repo1#WORKFLOW"
      }
    }
````

Thank you!

**Comment by obazoud** [comment]
Another question about the SDT with `dynamon-ts`.

I would like to create a Global Secondary Index on this table.
I don't find a way to do this.
How can I do this?

**Comment by chrisbarbour** [comment]
The best way to do this would be to set up a separate client that specifies the partition and sort key that can be used for the index, i plan to add support for this from the single table client soon

**Comment by obazoud** [comment]
Is there a way to backfill my object with the value of _partition_ and _sort_ computed by `dynamo-ts`after a `put`or a `batchPut`?
