### ISSUE TITLE
Support for sparse secondary indices

### ISSUE THREAD

**Issue by quinnromanek** [hexlabsio/dynamo-ts#47]
Dynamo doesn't require every record to have a value in a table's global secondary index (this is known as a sparse index).

It would be helpful to be able to define a table type with
```
type TableRecord = {
  gsiPk?: string;
  gsiSk?: string;
};
```

And then refer to `gsiPk` and `gsiSk` as the sort keys.  Right now optional string types are not acceptable as valid key types, so to create a sparse index you need to leverage multiple table definitions.  This is a fairly common pattern (it's used in AWS's examples extensively) so it would be nice to see it reflected in this package!

**Comment by chrisbarbour** [comment]
Hey @quinnromanek Thanks for the suggestion, this is definitely on our radar as something we would like to implement. If you think you could do it yourself, please submit a PR, we would love to see it! Otherwise we will be happy to implement soon.

**Comment by chrisbarbour** [comment]
@quinnromanek The latest version v6.0.187 now opens up the keys you can use for secondary indexes, hope this works for you
