### ISSUE TITLE
no delete in TablePartClient (single table design)

### ISSUE THREAD

**Issue by TheDanBlanco** [hexlabsio/dynamo-ts#53]
hey folks! i'm working with a single table design and my tables look like this (abbreviated):

```typescript
export type BaseTable = {
	pk: string;
	sk: string;
	gsi1pk: string;
	gsi1sk: string;
};

export const baseTableDefinition = TableDefinition.ofType<BaseTable>()
	.withPartitionKey("pk")
	.withSortKey("sk")
	.withGlobalSecondaryIndex("gsi1-index", "gsi1pk")
	.withSortKey("gsi1sk");

export type OrderBase = {
	order: string;
	email: string;
};

export const orderBase = TablePartInfo.from<OrderBase>().withKeys(
	"email",
	"order",
);

export type OrderProfile = OrderBase & {
	fullName: string;
	profile: string;
	address: string;
};

export const orderProfile = orderBase
	.childPart<OrderProfile>()
	.withKey("profile");
	
export const client = TablePartClient.fromPartsWithBaseTable(
  baseTableDefinition,
  config,
  orderProfile,
  // more items
);
```

`client.profile.delete` does not exist.

however, if i do:

```typescript
const deleteClient = TableClient.build(baseTableDefinition, config);
```

i can do deletes, but i have to reconstruct the pks myself, which isn't ideal.

do you have any guidance on this? am i doing something wrong in my config? i copied most of my tests from your tests, but there's nothing around deletes

**Comment by chrisbarbour** [comment]
Hey, thanks for using dynamo-ts! At present, this is how you would need to do a delete, I will work on a fix to add this to the single table clients and get back to you!

**Comment by chrisbarbour** [comment]
This has been added to version `@hexlabs/dynamo-ts@6.0.190` please try it and let me know it works for you, thanks again!
